### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by jeniara** [arduino-libraries/Arduino_MKRIoTCarrier#20]
I try to set individual sensitivity on buttons, but the example "Custom_Sensitivity.ino" does not compile. 

Arduino:1.8.13 (Windows Store 1.8.42.0) (Windows 10), Kort:"Arduino MKR WiFi 1010"
C:\Users\Joakim\Documents\Arduino\CarrierIOT\Individual_toutch_settings__jan27a\Individual_toutch_settings__jan27a.ino: In function 'void setup()':
Individual_toutch_settings__jan27a:21:19: error: 'class MKRIoTCarrier_Qtouch' has no member named 'updateConfig'
   carrier.Button0.updateConfig(threshold_btn_0);
                   ^~~~~~~~~~~~
exit status 1
'class MKRIoTCarrier_Qtouch' has no member named 'updateConfig'

I have the right version of the library... Happy to get suggestions!

**Comment by per1234** [comment]
Hi @jeniara the problem is that the version of the example sketch doesn't match with the version of the library you have installed. From the line number in your error message, I can see that you got the example sketch from the tip of this repository's `master` branch:
https://github.com/arduino-libraries/Arduino_MKRIoTCarrier/blob/master/examples/TouchPads/Custom_Sensitivity/Custom_Sensitivity.ino#L21
but you have the release version of the Arduino_MKRIoTCarrier library installed. Additional functionality has been added to the library since the last release, so the development version of the example sketch won't work with the release version of the library. You should always use matching versions. You will find the appropriate example sketches for the version of the library you have installed under the Arduino IDE's **File > Examples > Arduino_MKRIoTCarrier** menu.

**Comment by marqdevx** [comment]
Hey @jeniara Make sure you have the [MCHP_touch ](https://github.com/arduino-libraries/Arduino_MCHPTouch) updated too, you can do it by going to the Library Manager, and search "Arduino_MCHPTouch" look if you have the version 1.1.0

And the MKR IoT Carrier last version (v0.9.8)

Have a good one!

**Comment by jeniara** [comment]
@per1234, you are absolutely right, I was using not the example in the Arduino IDE, I'm impressed you took that from the line number! I could of cause wait until the library is release or I could try to install it manually, but I see on the release note the text "Added feature to set each buttons' sensitivity" but adding the line carrier.Button0.updateConfig(threshold) to the Arduino IDE example does not work. I'm not skilled enough to see from the code how to use the new feature - from differences in the code compared to the "master", if I would guess, I would say individual settings are actually not really implemented in v0.9.8. The feature is really needed to be able to use my Carrier as it has so different sensitivity on different buttons. I have last versions Arduino_MCHPTouch 1.1.0 and MKR IoT Carrier last version (v0.9.8). However, I guess I'd have to wait for the release of v0.9.9....
